### ISSUE TITLE
Bug when creating a new quiz

### ISSUE THREAD

**Issue by jsi** [enonic/app-xphoot#39]
Currently, selecting a folder and creating a new "game", causes an `IllegalArgumentException`.

The stacktrace looks like this:

```
22:51:54.118 ERROR c.e.x.j.i.e.JsonExceptionMapper - Incorrect property for content: /xphoot/sample-quizzes/__unnamed__
java.lang.IllegalArgumentException: Incorrect property for content: /xphoot/sample-quizzes/__unnamed__
	at com.enonic.xp.core.impl.content.CreateContentCommand.validatePropertyTree(CreateContentCommand.java:160)
	at com.enonic.xp.core.impl.content.CreateContentCommand.validateBlockingChecks(CreateContentCommand.java:126)
	at com.enonic.xp.core.impl.content.CreateContentCommand.doExecute(CreateContentCommand.java:89)
	at com.enonic.xp.core.impl.content.CreateContentCommand.execute(CreateContentCommand.java:76)
...
Caused by: com.enonic.xp.inputtype.InputTypeValidationException: Invalid value in [answer: one]: Value is not a valid option
	at com.enonic.xp.inputtype.InputTypeValidationException.invalidValue(InputTypeValidationException.java:34)
	at com.enonic.xp.inputtype.InputTypeBase.validateValue(InputTypeBase.java:70)
```

It is basically impossible to create a new quiz in any way, as this bug stops right after the first step of creating a quiz, with no more options available.

I first encountered this bug when trying to create a quiz on Enoic QA, but the exact same thing happens if I use the Enonic CLI, start a brand new instance, add the XPHoot app and try to create a quiz.

This applies to running xpHoot version 2.1.0 on XP 7.13.4.

**Comment by jsi** [comment]
I have tried v2.1.0 on XP 7.8.4.  It does not work either, but v2.0.0 works on XP 7.2.4.
